# Generated by Django 2.2 on 2020-01-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191203_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='restoran',
            field=models.SmallIntegerField(null=True),
        ),
    ]
