# Generated by Django 2.2 on 2020-01-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_worktimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktimes',
            name='hour_begin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='hour_end',
            field=models.TimeField(null=True),
        ),
    ]
