# Generated by Django 2.2 on 2020-05-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200415_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='color',
            field=models.CharField(blank=True, choices=[('empty', 'empty'), ('scanned', 'scanned'), ('ordered', 'ordered'), ('reordered', 'reordered'), ('order_accepted', 'order_accepted'), ('order_cancelled', 'order_cancelled'), ('reorder_accepted', 'reorder_accepted'), ('reorder_cancelled', 'reorder_cancelled'), ('bill_requested', 'bill_requested'), ('bill_closed', 'bill_closed')], default='empty', max_length=100),
        ),
    ]
