# Generated by Django 2.2 on 2020-06-21 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200507_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='restoran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Restoran'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'admin'), (1, 'worker'), (2, 'user'), (3, 'administration')], null=True, verbose_name='Status'),
        ),
    ]
