# Generated by Django 2.2 on 2019-12-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableproducts',
            name='recd',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'кабылданбады'), (2, 'кабылданды')], default=1),
        ),
    ]
