# Generated by Django 2.2 on 2020-05-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_tableproducts_recd'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableproducts',
            name='waiter',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
