# Generated by Django 2.2 on 2020-06-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_tableproducts_waiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableproducts',
            name='waiter',
        ),
        migrations.AddField(
            model_name='tableproducts',
            name='code_order',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
